[response_settings]
temperature = 0
max_tokens = 30384
max_completion_tokens = 80000
top_p = 1.0
frequency_penalty = 0.0
presence_penalty = 0.0
# reasoning_effort_transcript = low
reasoning_effort_refine = medium

[paths]
data_dir = /Volumes/Untitled/MeetingSecretaryAI_Data
zoom_dir = ~/Documents/Zoom
context_dir = /Volumes/Untitled/MeetingSecretaryAI_Data/context
output_dir = /Volumes/Untitled/MeetingSecretaryAI_Data/output
token_file = /Volumes/Untitled/MeetingSecretaryAI_Data/.hf_token.txt

[gui]
minutes_style = Action-Focused
output_format = DOCX
input_mode = zoom
include_rationale = false
include_recommendations = false
